# Spring配置
spring:
    # 模板引擎
    thymeleaf:
        mode: HTML
        encoding: utf-8
        # 禁用缓存
        cache: false
    # 资源信息
    messages:
        # 国际化资源文件路径
        basename: static/i18n/messages
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    profiles:
        active: druid
    # 文件上传
    servlet:
        multipart:
            # 单个文件大小
            max-file-size:  10MB
            # 设置总上传的文件大小
            max-request-size:  20MB
    # 服务模块
    devtools:
        restart:
            # 热部署开关
            enabled: true
# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.yiming.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

shiro:
    user:
        # 登录地址
        loginUrl: /login
        # 权限认证失败地址
        unauthorizedUrl: /unauth
        # 首页地址
        indexUrl: /index
        # 验证码开关
        captchaEnabled: true
        # 验证码类型 math 数组计算 char 字符
        captchaType: math
    cookie:
        # 设置Cookie的域名 默认空，即当前访问的域名
        domain:
        # 设置cookie的有效访问路径
        path: /
        # 设置HttpOnly属性
        httpOnly: true
        # 设置Cookie的过期时间，天为单位
        maxAge: 30